import:
    net.Indyuce.mmocore.api.player.PlayerData
    net.Indyuce.mmocore.manager.ClassManager
    net.Indyuce.mmocore.MMOCore
    net.Indyuce.mmocore.api.player.attribute.PlayerAttributes
    net.Indyuce.mmocore.api.player.attribute.PlayerAttribute

function resetAttribute(p: player) :: number:
    set {_mmoplayer} to PlayerData.get({_p})

    if {_mmoplayer} is not set:
        return 0

    set {_mmocore} to MMOCore.getPlugin(MMOCore.class)

    set {_attributeManagerField} to {_mmocore}.getClass().getDeclaredField("attributeManager")
    {_attributeManagerField}.setAccessible(true)
    set {_attributeManager} to {_attributeManagerField}.get({_mmocore})

    set {_attributeMapField} to {_attributeManager}.getClass().getDeclaredField("map")
    {_attributeMapField}.setAccessible(true)
    set {_attributeMap} to {_attributeMapField}.get({_attributeManager})

    set {_keySet} to {_attributeMap}.keySet()

    set {_totalATT} to 0

    loop numbers from 1 to {_keySet}.size():
        set {_attribute} to {_attributeMap}.get({_keySet}.toArray()[loop-number - 1])
        set {_attributeID} to {_attribute}.getId()
        set {_attributeValue} to {_mmoplayer}.getAttributes().getInstance({_attributeID}).getBase()
        {_mmoplayer}.getAttributes().getInstance({_attributeID}).setBase(0) # ✅ Reset ATT về 0
        add {_attributeValue} to {_totalATT}
    
    return {_totalATT}

command /upgradeclass <player> <text>:
    permission: op
    permission message: You must be an op to change player's permissions.
    executable by: console and players

    trigger:
        set {_player} to arg-1
        set {_classID} to arg-2 # ✅ Lấy ID class từ danh sách /debugclass

        set {_mmoplayer} to PlayerData.get({_player})
        set {_mmocore} to MMOCore.getPlugin(MMOCore.class) # ✅ Lấy instance MMOCore
        set {_classManagerField} to {_mmocore}.getClass().getDeclaredField("classManager") 
        {_classManagerField}.setAccessible(true) 
        set {_classManager} to {_classManagerField}.get({_mmocore}) # ✅ Lấy classManager

        set {_classMapField} to {_classManager}.getClass().getDeclaredField("map")
        {_classMapField}.setAccessible(true) 
        set {_classMap} to {_classMapField}.get({_classManager}) 

        set {_playerClass} to {_classMap}.get({_classID}) # ✅ Lấy class từ ID nhập vào

        if {_playerClass} is not set:
            stop
        
        set {_currentPlayerClass} to {_mmoplayer}.getProfess().getId() # ✅ Lấy class hiện tại của player

        
        if {_currentPlayerClass} is {_playerClass}.getId():
            set {_json} to "[{""text"": ""§cBạn đang sử dụng §6%{_playerClass}.getId()%§c rồi! Không thể đổi trùng class.""}]"
            execute console command "tellraw %{_player}% %{_json}%"
            stop

        set {_totalATT} to resetAttribute({_player}) # ✅ Reset ATT về 0

        {_mmoplayer}.giveAttributePoints({_totalATT})
        
        
        {_mmoplayer}.setClass({_playerClass})
        {_mmoplayer}.setLevel(1)
        {_mmoplayer}.setExperience(0)

        execute console command "tellraw %{_player}% [{""text"": ""§aBạn đã chuyển đổi thành công class: §b%{_classID}%""}]"
        if {_totalATT} > 0:
            execute console command "tellraw %{_player}% [{""text"": ""§eTất cả điểm thuộc tính trước đây đã được hoàn trả: §b%{_totalATT}% §eAttribute Points!""}]"
        
