import:
	io.lumine.mythic.lib.api.item.NBTItem

command /checkench <player>:
	trigger:
		set {_p} to arg-1
		set {_slotnum} to 0
		loop all items in {_p}'s inventory:
			if loop-value is not air:
				set {_realitem} to item in loop-value
				set {_nbt} to try NBTItem.get({_realitem})
				set {_id} to ""
				if {_nbt} is set:
					set {_id} to try {_nbt}.getString("MMOITEMS_ITEM_ID")
				if {_id} is "PICKAXE_UPGTEST":
					send "slot#%{_slotnum}%: %{_realitem}% | id=%{_id}% | efficiency level=%level of efficiency of {_realitem}%" to console
			add 1 to {_slotnum}
